
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: xenial
      sudo: false

addons:
  apt:
    packages:
      - autopoint
      - intltool
      # DRM
      - libdrm-dev
      # RANDR
      - libxcb1-dev
      - libxcb-randr0-dev
      # VidMode
      - libx11-dev
      - libxxf86vm-dev
      # Wayland
      - libwayland-dev
      # GeoClue2
      - libglib2.0-dev
      # GUI
      - python3

install:
  - ./bootstrap
  - mkdir "$TRAVIS_BUILD_DIR/root"
  - |
    ./configure --prefix="$TRAVIS_BUILD_DIR/root" --enable-drm --enable-vidmode --enable-randr --enable-geoclue2 --enable-gui --enable-apparmor --with-systemduserunitdir=no
  - make -j2 install
  - make -j2 distcheck

script:
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/gammastep -l 12:-34 -pv
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/gammastep -l 12:-34 -m dummy -vo
  - |
    echo -e "[general]\ndawn-time=6:30\ndusk-time=18:00-19:30" > time.config
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/gammastep -c time.config -pv
  - |
    "$TRAVIS_BUILD_DIR"/root/bin/gammastep -c time.config -m dummy -vo
